export const categories = [
  { id: "motor", name: "Motor", count: 24 },
  { id: "suspension", name: "Suspensión", count: 18 },
  { id: "frenos", name: "Frenos", count: 15 },
  { id: "electrico", name: "Eléctrico", count: 12 },
  { id: "transmision", name: "Transmisión", count: 9 },
  { id: "carroceria", name: "Carrocería", count: 21 },
]

export const brands = [
  { id: "hyundai", name: "Hyundai", count: 32 },
  { id: "kia", name: "Kia", count: 28 },
  { id: "ssangyong", name: "SsangYong", count: 15 },
  { id: "daewoo", name: "Daewoo", count: 12 },
  { id: "chevrolet", name: "Chevrolet", count: 8 },
]

export const products = [
  {
    id: "1",
    name: "Filtro de Aceite Premium",
    sku: "FO-HYU-001",
    category: "motor",
    categoryName: "Motor",
    brand: "hyundai",
    brandName: "Hyundai",
    compatibility: ["Tucson 2015-2020", "Elantra 2016-2021", "Santa Fe 2018-2023"],
    image: "/oil-filter-automotive-part.jpg",
    inStock: true,
  },
  {
    id: "2",
    name: "Pastillas de Freno Delanteras",
    sku: "PF-KIA-002",
    category: "frenos",
    categoryName: "Frenos",
    brand: "kia",
    brandName: "Kia",
    compatibility: ["Sportage 2016-2022", "Sorento 2015-2020", "Optima 2017-2021"],
    image: "/brake-pads-automotive-ceramic.jpg",
    inStock: true,
  },
  {
    id: "3",
    name: "Amortiguador Trasero",
    sku: "AM-HYU-003",
    category: "suspension",
    categoryName: "Suspensión",
    brand: "hyundai",
    brandName: "Hyundai",
    compatibility: ["Accent 2012-2019", "i30 2014-2020"],
    image: "/rear-shock-absorber-car-suspension.jpg",
    inStock: true,
  },
  {
    id: "4",
    name: "Alternador 12V 90A",
    sku: "AL-KIA-004",
    category: "electrico",
    categoryName: "Eléctrico",
    brand: "kia",
    brandName: "Kia",
    compatibility: ["Rio 2015-2021", "Cerato 2016-2020", "Picanto 2017-2022"],
    image: "/car-alternator-electrical-automotive.jpg",
    inStock: false,
  },
  {
    id: "5",
    name: "Kit de Embrague Completo",
    sku: "KE-SSY-005",
    category: "transmision",
    categoryName: "Transmisión",
    brand: "ssangyong",
    brandName: "SsangYong",
    compatibility: ["Korando 2014-2019", "Rexton 2015-2021"],
    image: "/car-clutch-kit-transmission-parts.jpg",
    inStock: true,
  },
  {
    id: "6",
    name: "Espejo Lateral Derecho",
    sku: "EL-HYU-006",
    category: "carroceria",
    categoryName: "Carrocería",
    brand: "hyundai",
    brandName: "Hyundai",
    compatibility: ["Tucson 2016-2021", "Santa Fe 2017-2022"],
    image: "/car-side-mirror-right-automotive.jpg",
    inStock: true,
  },
  {
    id: "7",
    name: "Bomba de Agua",
    sku: "BA-DAE-007",
    category: "motor",
    categoryName: "Motor",
    brand: "daewoo",
    brandName: "Daewoo",
    compatibility: ["Matiz 2005-2015", "Spark 2010-2017"],
    image: "/water-pump-car-engine-cooling.jpg",
    inStock: true,
  },
  {
    id: "8",
    name: "Discos de Freno Ventilados",
    sku: "DF-KIA-008",
    category: "frenos",
    categoryName: "Frenos",
    brand: "kia",
    brandName: "Kia",
    compatibility: ["Sportage 2018-2023", "Seltos 2020-2024"],
    image: "/ventilated-brake-discs-rotors-automotive.jpg",
    inStock: true,
  },
  {
    id: "9",
    name: "Bujías de Encendido (4 unidades)",
    sku: "BU-CHE-009",
    category: "motor",
    categoryName: "Motor",
    brand: "chevrolet",
    brandName: "Chevrolet",
    compatibility: ["Spark GT 2012-2020", "Sail 2014-2019"],
    image: "/spark-plugs-ignition-car-engine.jpg",
    inStock: true,
  },
  {
    id: "10",
    name: "Terminal de Dirección",
    sku: "TD-HYU-010",
    category: "suspension",
    categoryName: "Suspensión",
    brand: "hyundai",
    brandName: "Hyundai",
    compatibility: ["Elantra 2015-2020", "Sonata 2016-2021", "Kona 2018-2023"],
    image: "/tie-rod-end-steering-suspension-car.jpg",
    inStock: false,
  },
  {
    id: "11",
    name: "Faro Delantero LED Izquierdo",
    sku: "FD-KIA-011",
    category: "carroceria",
    categoryName: "Carrocería",
    brand: "kia",
    brandName: "Kia",
    compatibility: ["Sportage 2019-2024"],
    image: "/led-headlight-car-front-light.jpg",
    inStock: true,
  },
  {
    id: "12",
    name: "Sensor de Oxígeno",
    sku: "SO-SSY-012",
    category: "electrico",
    categoryName: "Eléctrico",
    brand: "ssangyong",
    brandName: "SsangYong",
    compatibility: ["Actyon 2013-2018", "Korando 2015-2020"],
    image: "/oxygen-sensor-o2-car-exhaust.jpg",
    inStock: true,
  },
]
